
export const icons = {
    error:            'error',
    twitter:          'mdi:twitter',
    discord:          'simple-icons:discord',
    docs:             'mdi:file-document',
    github:           'mdi:github',
    download:         'mdi:download',
    browse:           'mdi:database-search',
    gd:               '@:gd-logo',
    examples:         'mdi:text-search',
    graph:            'mdi:graph-line',
    windows:          'mdi:microsoft-windows',
    mac:              'mdi:apple',
    android:          'mdi:android',
    ios:              'mdi:apple-ios',
    linux:            'mdi:linux',
    copyright:        'mdi:copyright',
    help:             'mdi:help-circle',
    warning:          'mdi:warning-circle',
    down:             'mdi:chevron-down',
    one:              'mdi:number-one-circle',
    two:              'mdi:number-two-circle',
    three:            'mdi:number-three-circle',
    four:             'mdi:number-four-circle',
    home:             'mdi:home',
    search:           'mdi:search',
    time:             'mdi:clock',
    'time-update':    'mdi:update',
    sort:             'mdi:sort',
    'sort-downloads': 'mdi:sort-numeric-descending',
    'sort-recent':    'mdi:sort-clock-descending',
    tags:             'mdi:tag',
    'tags-clear':     'mdi:tag-off',
    filter:           'mdi:filter',
    'filter-clear':   'mdi:filter-off',
    featured:         'mdi:star',

    'tag-universal':        'mdi:globe',
    'tag-gameplay':         'mdi:gamepad-variant',
    'tag-editor':           'mdi:hammer-wrench',
    'tag-offline':          'mdi:offline',
    'tag-online':           'mdi:cloud',
    'tag-enhancement':      'mdi:magic',
    'tag-music':            'mdi:music-note',
    'tag-interface':        'mdi:interaction-tap',
    'tag-bugfix':           'mdi:bug',
    'tag-utility':          'mdi:wrench',
    'tag-performance':      'mdi:clock-fast',
    'tag-customization':    'mdi:paint-outline',
    'tag-content':          'mdi:auto-stories',
    'tag-developer':        'mdi:code-braces',
};
export type KnownIcon = keyof typeof icons;
